// This file is @generated by prost-build.
/// Order book level structure
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderBookLevel {
    #[prost(double, tag = "1")]
    pub price: f64,
    #[prost(double, tag = "2")]
    pub quantity: f64,
    #[prost(int32, tag = "3")]
    pub order_count: i32,
    #[prost(double, tag = "4")]
    pub min_qty: f64,
    #[prost(message, repeated, tag = "5")]
    pub additional_info: ::prost::alloc::vec::Vec<AdditionalInfo>,
}
/// Security definition attributes
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SecurityAttribute {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
}
/// Additional information for security definition extension
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AdditionalInfo {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(int32, tag = "2")]
    pub semantic_type: i32,
    #[prost(int32, repeated, tag = "3")]
    pub value: ::prost::alloc::vec::Vec<i32>,
}
/// Update entry for order book updates
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderBookUpdateEntry {
    #[prost(double, tag = "1")]
    pub price: f64,
    #[prost(double, tag = "2")]
    pub quantity: f64,
    #[prost(int32, tag = "3")]
    pub order_count: i32,
    #[prost(double, tag = "4")]
    pub min_qty: f64,
    #[prost(message, repeated, tag = "5")]
    pub additional_info: ::prost::alloc::vec::Vec<AdditionalInfo>,
}
/// Base message wrapper
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MarketDataMessage {
    /// Metadata
    #[prost(int64, tag = "100")]
    pub timestamp_nanos: i64,
    #[prost(string, tag = "101")]
    pub message_id: ::prost::alloc::string::String,
    #[prost(
        oneof = "market_data_message::MessageType",
        tags = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15"
    )]
    pub message_type: ::core::option::Option<market_data_message::MessageType>,
}
/// Nested message and enum types in `MarketDataMessage`.
pub mod market_data_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum MessageType {
        #[prost(message, tag = "1")]
        Heartbeat(super::Heartbeat),
        #[prost(message, tag = "2")]
        UnsequencedHeartbeat(super::UnsequencedHeartbeat),
        #[prost(message, tag = "3")]
        OrderBookSnapshot(super::OrderBookSnapshot),
        #[prost(message, tag = "4")]
        OrderBookUpdate(super::OrderBookUpdate),
        #[prost(message, tag = "5")]
        Trade(super::Trade),
        #[prost(message, tag = "6")]
        SecurityDefinition(super::SecurityDefinition),
        #[prost(message, tag = "7")]
        SecurityDefinitionExtension(super::SecurityDefinitionExtension),
        #[prost(message, tag = "8")]
        SecurityStatus(super::SecurityStatus),
        #[prost(message, tag = "9")]
        RequestReject(super::RequestReject),
        #[prost(message, tag = "10")]
        RequestAccept(super::RequestAccept),
        #[prost(message, tag = "11")]
        SnapshotRequest(super::SnapshotRequest),
        #[prost(message, tag = "12")]
        TradesRequest(super::TradesRequest),
        #[prost(message, tag = "13")]
        SecurityDefinitionRequest(super::SecurityDefinitionRequest),
        #[prost(message, tag = "14")]
        ClientDisconnectRequest(super::ClientDisconnectRequest),
        #[prost(message, tag = "15")]
        UnknownMessage(super::UnknownMessage),
    }
}
/// Template 0: Heartbeat
///
/// Empty message - just indicates connection is alive
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Heartbeat {}
/// Template 10: Unsequenced Heartbeat
///
/// Empty message - unsequenced keep-alive
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UnsequencedHeartbeat {}
/// Templates 4 & 15: Order Book Snapshot (with/without scaling)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderBookSnapshot {
    #[prost(int32, tag = "1")]
    pub security_id: i32,
    #[prost(int32, tag = "2")]
    pub venue_id: i32,
    #[prost(int64, tag = "3")]
    pub timestamp: i64,
    #[prost(message, repeated, tag = "4")]
    pub bids: ::prost::alloc::vec::Vec<OrderBookLevel>,
    #[prost(message, repeated, tag = "5")]
    pub asks: ::prost::alloc::vec::Vec<OrderBookLevel>,
}
/// Order Book Update (incremental updates)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderBookUpdate {
    #[prost(message, optional, tag = "1")]
    pub book: ::core::option::Option<OrderBookSnapshot>,
    #[prost(message, repeated, tag = "2")]
    pub updates: ::prost::alloc::vec::Vec<OrderBookUpdateEntry>,
}
/// Templates 5 & 16: Trade (with/without scaling)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Trade {
    #[prost(int32, tag = "1")]
    pub security_id: i32,
    #[prost(int32, tag = "2")]
    pub venue_id: i32,
    #[prost(double, tag = "3")]
    pub price: f64,
    #[prost(double, tag = "4")]
    pub quantity: f64,
    #[prost(int64, tag = "5")]
    pub timestamp: i64,
    #[prost(string, tag = "6")]
    pub trade_id: ::prost::alloc::string::String,
    #[prost(enumeration = "AggressorSide", tag = "7")]
    pub aggressor_side: i32,
    #[prost(string, repeated, tag = "8")]
    pub conditions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "9")]
    pub additional_info: ::prost::alloc::vec::Vec<AdditionalInfo>,
}
/// Template 8: Security Definition
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SecurityDefinition {
    #[prost(int32, tag = "1")]
    pub security_id: i32,
    #[prost(string, tag = "2")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub security_type: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub currency: ::prost::alloc::string::String,
    #[prost(double, tag = "5")]
    pub lot_size: f64,
    #[prost(double, tag = "6")]
    pub tick_size: f64,
    #[prost(double, tag = "7")]
    pub display_factor: f64,
    #[prost(enumeration = "SecurityTradingStatus", tag = "8")]
    pub trading_status: i32,
    #[prost(message, repeated, tag = "9")]
    pub attributes: ::prost::alloc::vec::Vec<SecurityAttribute>,
}
/// Template 17: Security Definition Extension
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SecurityDefinitionExtension {
    #[prost(int32, tag = "1")]
    pub security_id: i32,
    #[prost(string, tag = "2")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub additional_info: ::prost::alloc::vec::Vec<AdditionalInfo>,
}
/// Template 6: Security Status
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SecurityStatus {
    #[prost(int32, tag = "1")]
    pub security_id: i32,
    #[prost(enumeration = "SecurityTradingStatus", tag = "2")]
    pub status: i32,
}
/// Template 1: Request Reject
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RequestReject {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
}
/// Template 11: Request Accept
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RequestAccept {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub md_stream_id: i32,
    #[prost(int32, repeated, tag = "3")]
    pub security_ids: ::prost::alloc::vec::Vec<i32>,
}
/// Template 2: Snapshot Request
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SnapshotRequest {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(enumeration = "SubscriptionRequestType", tag = "2")]
    pub subscription_type: i32,
    #[prost(int32, tag = "3")]
    pub venue_id: i32,
    #[prost(int32, tag = "4")]
    pub security_id: i32,
    #[prost(int32, tag = "5")]
    pub market_depth: i32,
}
/// Template 3: Trades Request
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TradesRequest {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(enumeration = "SubscriptionRequestType", tag = "2")]
    pub subscription_type: i32,
    #[prost(int32, tag = "3")]
    pub venue_id: i32,
    #[prost(int32, tag = "4")]
    pub security_id: i32,
}
/// Template 7: Security Definition Request
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SecurityDefinitionRequest {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(enumeration = "SecurityRequestType", tag = "2")]
    pub request_type: i32,
    #[prost(string, tag = "3")]
    pub symbol: ::prost::alloc::string::String,
}
/// Template 14: Client Disconnect Request
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientDisconnectRequest {
    #[prost(string, tag = "1")]
    pub reason: ::prost::alloc::string::String,
}
/// Unknown message handling
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UnknownMessage {
    #[prost(int32, tag = "1")]
    pub template_id: i32,
    #[prost(int32, tag = "2")]
    pub data_size: i32,
}
/// Common types and enums
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AggressorSide {
    AggressorUnknown = 0,
    AggressorBuy = 1,
    AggressorSell = 2,
}
impl AggressorSide {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::AggressorUnknown => "AGGRESSOR_UNKNOWN",
            Self::AggressorBuy => "AGGRESSOR_BUY",
            Self::AggressorSell => "AGGRESSOR_SELL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "AGGRESSOR_UNKNOWN" => Some(Self::AggressorUnknown),
            "AGGRESSOR_BUY" => Some(Self::AggressorBuy),
            "AGGRESSOR_SELL" => Some(Self::AggressorSell),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SecurityTradingStatus {
    SecurityStatusUnknown = 0,
    SecurityStatusTrading = 1,
    SecurityStatusSuspended = 2,
    SecurityStatusHalted = 3,
    SecurityStatusClosed = 4,
}
impl SecurityTradingStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::SecurityStatusUnknown => "SECURITY_STATUS_UNKNOWN",
            Self::SecurityStatusTrading => "SECURITY_STATUS_TRADING",
            Self::SecurityStatusSuspended => "SECURITY_STATUS_SUSPENDED",
            Self::SecurityStatusHalted => "SECURITY_STATUS_HALTED",
            Self::SecurityStatusClosed => "SECURITY_STATUS_CLOSED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SECURITY_STATUS_UNKNOWN" => Some(Self::SecurityStatusUnknown),
            "SECURITY_STATUS_TRADING" => Some(Self::SecurityStatusTrading),
            "SECURITY_STATUS_SUSPENDED" => Some(Self::SecurityStatusSuspended),
            "SECURITY_STATUS_HALTED" => Some(Self::SecurityStatusHalted),
            "SECURITY_STATUS_CLOSED" => Some(Self::SecurityStatusClosed),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SubscriptionRequestType {
    SubscriptionUnknown = 0,
    SubscriptionSnapshot = 1,
    SubscriptionSnapshotAndUpdates = 2,
    SubscriptionUnsubscribe = 3,
}
impl SubscriptionRequestType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::SubscriptionUnknown => "SUBSCRIPTION_UNKNOWN",
            Self::SubscriptionSnapshot => "SUBSCRIPTION_SNAPSHOT",
            Self::SubscriptionSnapshotAndUpdates => "SUBSCRIPTION_SNAPSHOT_AND_UPDATES",
            Self::SubscriptionUnsubscribe => "SUBSCRIPTION_UNSUBSCRIBE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SUBSCRIPTION_UNKNOWN" => Some(Self::SubscriptionUnknown),
            "SUBSCRIPTION_SNAPSHOT" => Some(Self::SubscriptionSnapshot),
            "SUBSCRIPTION_SNAPSHOT_AND_UPDATES" => {
                Some(Self::SubscriptionSnapshotAndUpdates)
            }
            "SUBSCRIPTION_UNSUBSCRIBE" => Some(Self::SubscriptionUnsubscribe),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SecurityRequestType {
    SecurityRequestUnknown = 0,
    SecurityRequestAllSecurities = 1,
    SecurityRequestSpecificSecurity = 2,
}
impl SecurityRequestType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::SecurityRequestUnknown => "SECURITY_REQUEST_UNKNOWN",
            Self::SecurityRequestAllSecurities => "SECURITY_REQUEST_ALL_SECURITIES",
            Self::SecurityRequestSpecificSecurity => "SECURITY_REQUEST_SPECIFIC_SECURITY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SECURITY_REQUEST_UNKNOWN" => Some(Self::SecurityRequestUnknown),
            "SECURITY_REQUEST_ALL_SECURITIES" => Some(Self::SecurityRequestAllSecurities),
            "SECURITY_REQUEST_SPECIFIC_SECURITY" => {
                Some(Self::SecurityRequestSpecificSecurity)
            }
            _ => None,
        }
    }
}
